- image_id: 1
  name: Skellet
  src: img/legendary/skellet.png

- image_id: 2
  name: DogZilla
  src: img/legendary/dogzilla.png

- image_id: 3
  name: Ghost
  src: img/legendary/ghost.png

- image_id: 4
  name: To Be Dropped
  src: img/legendary/tobedropped.png

- image_id: 5
  name: To Be Dropped
  src: img/legendary/tobedropped.png

- image_id: 6
  name: To Be Dropped
  src: img/legendary/tobedropped.png

- image_id: 7
  name: To Be Dropped
  src: img/legendary/tobedropped.png

- image_id: 8
  name: Yeti
  src: img/legendary/yeti.png

- image_id: 9
  name: To Be Dropped
  src: img/legendary/tobedropped.png
